### ISSUE TITLE
Kein klares Verhalten ohne Adminrechte

### ISSUE THREAD

**Issue by thtomate** [whentze/dartbot#2]
Es sollte kontrolliert werden, dass der Bot Adminrechte hat. Es gibt auch andere Supergeuppen

**Comment by Bergiu** [comment]
Ist es eine ausreichende Lösung, einfach bei restrict_user den return zu prüfen ob der false ist? Also wenn der bot nicht bannen konnte, dann gibt es als return false zurück und darauf folgend kann man eine Fehlermeldung ausgeben.

**Comment by Bergiu** [comment]
Alternativ müsste man vorher prüfen ob der bot die notwendigen rechte hat und das ist komplizierter
