### ISSUE TITLE
Bot ignoriert Basketbälle und Würfel

### ISSUE THREAD

**Issue by vimpostor** [whentze/dartbot#3]
Zitat:
```
wer ne 6 würfelt, das bullseye trifft oder nen swisher macht, wird gekickt
```

**Erwartetes Verhalten:**
Ich werde gemutet, wenn ich ne 6 würfel.

**Tatsächliches Verhalten:**
Der Bot verwertet nur Darts.

**System Informationen:**
Betriebssystem: Arch Linux 5.7.8 btw

**Comment by thtomate** [comment]
Aktuellere Aussage: https://t.me/RWTHInformatik/479791

**Comment by whentze** [comment]
Das beobachtete Verhalten kann ich bei mir reproduzieren, es handelt sich aber nicht um einen Bug.

Der Bot ist (wie der Name andeutet) nur dazu gedacht, erfolgreiche Dart-Spieler zu belohnen. Das liegt daran, dass er entsprechend der UNIX-Philosohpie designt ist und daher immer nur eine Sache machen kann.

**Comment by vimpostor** [comment]
Hallo Herr Entwickler,

vielen dank für die schnelle Rückmeldung, das ist schade aber ich kann es verstehen.

Ich schließe dann mal den Faden hier...

**Comment by valkum** [comment]
Entsprechend er Gepflogenheiten auf GitHub möchte ich auf dieses geschlossene Issue antworten und fragen wann denn der BallBot und der WürfelBot aus dem hause whentze kommen?

+1
